# Generated by Django 4.2.4 on 2023-09-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=150, verbose_name='theme name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, verbose_name='post name')),
                ('slug', models.CharField(max_length=20, unique=True, verbose_name='slug')),
                ('containment', models.TextField(verbose_name='containment')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='preview')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='change date')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.theme', verbose_name='theme')),
            ],
        ),
    ]
