# Generated by Django 4.2.4 on 2023-09-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
