# Generated by Django 4.2.4 on 2023-10-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_changed_at_remove_post_theme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='name',
        ),
    ]
