# Generated by Django 4.2.4 on 2023-09-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='category name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='product name')),
                ('description', models.TextField(verbose_name='description')),
                ('preview', models.ImageField(upload_to='products_images', verbose_name='preview')),
                ('price', models.FloatField(verbose_name='price')),
                ('created_at', models.DateTimeField(verbose_name='creation date')),
                ('changed_at', models.DateTimeField(verbose_name='change date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
    ]
