# Generated by Django 4.2.4 on 2023-09-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=150, verbose_name='theme name')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, verbose_name='post name')),
                ('slug', models.CharField(max_length=20, verbose_name='slug')),
                ('containment', models.TextField(verbose_name='containment')),
                ('preview', models.ImageField(upload_to='products_images', verbose_name='preview')),
                ('created_at', models.DateTimeField(verbose_name='creation date')),
                ('changed_at', models.DateTimeField(verbose_name='change date')),
                ('views_count', models.IntegerField(verbose_name='views count')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.theme', verbose_name='theme')),
            ],
        ),
    ]
