# Generated by Django 4.2.4 on 2023-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_theme_alter_product_category_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=20, unique=True, verbose_name='slug'),
        ),
    ]
