# Generated by Django 4.2.4 on 2023-09-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_post_changed_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='views count'),
        ),
    ]
