# Generated by Django 4.2.4 on 2023-09-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_delete_post_delete_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
