# Generated by Django 4.2.4 on 2023-10-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
