# Generated by Django 4.2.4 on 2023-10-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_changed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='version_number',
            new_name='number',
        ),
    ]
